name: fsdl-text-recognizer-2021
channels:
  - defaults
dependencies:
  - python=3.6  # Google Colab is still on Python 3.6
  - pip
  
  - pip:
    - pip-tools
    - cudatoolkit=11.1
    - cudnn=7.6
    
